apiVersion: v1
kind: Service
metadata:
  name: skillcode-backend-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  selector:
    app: skillcode-backend-pod
