apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillcode-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillcode-backend-pod
  template: # pod spec
    metadata:
      labels:
        app: skillcode-backend-pod
    spec:
      containers: # container spec
      - name: backend-container
        image: {{ .Values.backend.image }}
        imagePullSecrets:
          - name: {{ .Values.imagePullSecret.name | quote }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: CLUSTER_PORT
          value: {{ .Values.backend.clusterPort | quote }}
        - name: KIND_SERVER_URL
          value: {{ .Values.backend.kindServerUrl | quote }}
        - name: MONGO_URI
          value: {{ .Values.backend.mongoUri | quote }}
        - name: MONGO_DB
          value: {{ .Values.backend.mongoDb | quote }}
        - name: KUBECONFIG
          value: {{ .Values.backend.kubeconfig | quote }}
        - name: PORT
          value: {{ .Values.backend.port | quote }}
        - name: MODE_ENV
          value: {{ .Values.backend.modeEnv | quote }}