apiVersion: v1
kind: Service
metadata:
  name: skillcode-frontend-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: skillcode-frontend-pod
