apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-pod
  template: # pod spec
    metadata:
      labels:
        app: mongo-pod
    spec: # container spec
      containers:
        - name: mongo-container
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          emptyDir: {} # Use emptyDir for testing; replace with PersistentVolumeClaim for production.
