apiVersion: v1
kind: Service 
metadata:
  name: mongo-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
  selector:
    app: mongo-pod
