apiVersion: v1
kind: ConfigMap
metadata:
  name: seed-scripts
data:
  requirements.txt: |
    pymongo
  drop_post.py: |
    import os
    import json
    from pymongo import MongoClient

    # Fetch environment variables
    MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
    DATABASE_NAME = os.getenv("DATABASE_NAME", "skillcode_db")
    COLLECTION_NAME = "questions"

    # Read questions from questions.json
    with open('/seed_scripts/questions.json', 'r') as file:
        questions = json.load(file)

    # Select 10 questions
    data = questions[:10]

    # Connect to MongoDB
    client = MongoClient(MONGO_URI)
    db = client[DATABASE_NAME]
    collection = db[COLLECTION_NAME]

    # Drop the collection if it exists
    collection.drop()

    # Insert seed data
    collection.insert_many(data)

    print(f"Seeded {len(data)} documents into the '{COLLECTION_NAME}' collection.")
  questions.json: |
    [
      {
        "title": "Two Sum",
        "description": "Given an array of integers, return indices of the two numbers such that they add up to a specific target.",
        "difficulty": "Easy",
        "category": "Array",
        "stats": 0,
        "examples": [
          {
            "parameters": [
              "[2, 7, 11, 15]",
              "9"
            ],
            "expected_output": "[0, 1]"
          }
        ],
        "test_cases": [
          {
            "parameters": [
              "[3, 2, 4]",
              "6"
            ],
            "expected_output": "[1, 2]"
          }
        ],
        "function_config": {
          "name": "twoSum",
          "parameters": [
            {
              "name": "nums",
              "param_type": {
                "type": "Array",
                "type_children": {
                  "type": "Integer"
                }
              }
            },
            {
              "name": "target",
              "param_type": {
                "type": "Integer"
              }
            }
          ],
          "return_type": {
            "type": "Array",
            "type_children": {
              "type": "Integer"
            }
          }
        },
        "languages": [
          "JavaScript",
          "Python"
        ]
      },
      {
        "title": "Reverse String",
        "description": "Write a function that reverses a string.",
        "difficulty": "Easy",
        "category": "String",
        "stats": 0,
        "examples": [
          {
            "parameters": [
              "\"hello\""
            ],
            "expected_output": "\"olleh\""
          }
        ],
        "test_cases": [
          {
            "parameters": [
              "\"world\""
            ],
            "expected_output": "\"dlrow\""
          }
        ],
        "function_config": {
          "name": "reverseString",
          "parameters": [
            {
              "name": "s",
              "param_type": {
                "type": "String"
              }
            }
          ],
          "return_type": {
            "type": "String"
          }
        },
        "languages": [
          "JavaScript",
          "Python"
        ]
      }
    ]
