apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db-job
spec:
  template:
    spec:
      containers:
        - name: seed-db-container
          image: {{ .Values.seedDb.image }}
          env:
            - name: MONGO_URI
              value: {{ .Values.seedDb.mongoUri | quote }}
            - name: DATABASE_NAME
              value: {{ .Values.seedDb.databaseName | quote }}
          command:
            [
              "sh",
              "-c",
              "pip install -r /seed_scripts/requirements.txt && python /seed_scripts/drop_post.py",
            ]
          volumeMounts:
            - name: seed-scripts
              mountPath: /seed_scripts
      volumes:
        - name: seed-scripts
          configMap:
            name: seed-scripts
      restartPolicy: OnFailure
