apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: try
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 3000
      command: ["nginx", "-g", "daemon off;"]
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
  volumes:
    - name: nginx-config
      configMap:
        name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: try
data:
  nginx.conf: |
    events { }
    http {
      server {
        listen 3000;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
