apiVersion: v1
kind: Service
metadata:
  name: nuxt-app-service
spec:
  type: NodePort
  selector:
    app: nuxt-app
  ports:
    - protocol: TCP
      port: 3000         # Service port for external traffic
      targetPort: 3000   # Port on the Pod where Nuxt is running
      nodePort: 30036    # NodePort for external access
