apiVersion: apps/v1
kind: Deployment
metadata:
  name: skillcode-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skillcode-backend-pod
  template: # pod spec
    metadata:
      labels:
        app: skillcode-backend-pod
    spec:
      containers: # container spec
      - name: backend-container
        image: tehilathestudent/skillcode-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: CLUSTER_PORT
          value: "37000"
        - name: KIND_SERVER_URL
          value: "https://host.docker.internal"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017"
        - name: MONGO_DB
          value: "skillcode_db"
        - name: KUBECONFIG
          value: "/root/.kube/config"
        - name: PORT
          value: "8080"
        - name: MODE_ENV
          value: "development"